### ISSUE TITLE
Consider Removing XcodeColor info from log

### ISSUE THREAD

**Issue by mohpor** [delba/Log#17]
Hi,
Unfortunately Xcode won't support plugins anymore and we are left with no XcodeColor.
Log still tries to add color info to console logs and that makes an ugly (and sad) console.

I thing the colorization should become optional (with room left for possible future support for XcodeColor)

Thoughts?

**Comment by delba** [comment]
Did you try setting the theme to nil?

**Comment by mohpor** [comment]
Oh well ...
Sorry to bother.

**Comment by gwigz** [comment]
It's still suggested to use XcodeColors on the main branch, of which is only Xcode 3 compatible?

Also, somewhat related; is there any method of changing the labels, to achieve something like: https://github.com/robbiehanson/XcodeColors/issues/88#issuecomment-248256673?

**Comment by delba** [comment]
Hi @gwigz,

This is a great idea and I'm gonna try to implement it this weekend if I find the time :)
Also, as @mohpor suggested, I'm going to remove the default theme so that you won't have to write `logger.theme = nil`. 

By the way, the XcodeColors project linked in the README is a fork of the original and worked very well with Xcode 7: https://github.com/robbiehanson/XcodeColors
You might want to take a look at [MakeXcodeGr8Again](https://github.com/fpg1503/MakeXcodeGr8Again) to use plugins with Xcode 8. I can't live without it!
